<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="129860" started-at="2018-04-02T03:24:56Z" finished-at="2018-04-02T03:27:06Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.ProjectRunner@a74868d]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="129860" started-at="2018-04-02T03:24:56Z" finished-at="2018-04-02T03:27:06Z">
      <class name="runner.ProjectRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runner.ProjectRunner@a74868d]" name="setUpClass" is-config="true" duration-ms="641" started-at="2018-04-02T03:24:56Z" finished-at="2018-04-02T03:24:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.ProjectRunner@a74868d]" name="feature" duration-ms="82844" started-at="2018-04-02T03:24:57Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-04-02T03:26:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[To Test the Signup Feature of Website]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.ProjectRunner@a74868d]" name="feature" duration-ms="45200" started-at="2018-04-02T03:26:20Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-04-02T03:27:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[To Test the login functionality of website]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.loginsteps.Loginsteps.i_validate_error_message_for_scenario(Loginsteps.java:46)
at âœ½.Then I validate error message for scenario(login.feature:15)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="ReportSetUp()[pri:0, instance:runner.ProjectRunner@a74868d]" name="ReportSetUp" is-config="true" duration-ms="257" started-at="2018-04-02T03:27:05Z" finished-at="2018-04-02T03:27:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportSetUp -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runner.ProjectRunner@a74868d]" name="tearDownClass" is-config="true" duration-ms="675" started-at="2018-04-02T03:27:06Z" finished-at="2018-04-02T03:27:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.ProjectRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
